colors:
  gray_dk: &bg '#2F343F'
  gray_dk2: '#4c566a'
  gray: '#a9a9a9'
  gray_lt: &fg '#c0c5ce'
  orange: '#fba922'
  blue_1: '#3384d0'
  blue_2: &accent '#6790eb'
  blue_3: '#4c566a'
  white: '#f3f4f5'
  red: '#cd1f3f'
  green: '#62FF00'

bar_attrs:
  font: &font Hack
  fontsize: &font_size 26
  foreground: *fg
  gap: &gap 20

layout_theme:
  margin: *gap
  border_width: 0

dropdown_theme:
  opacity: 1.
  height: 0.85
  width: 0.85
  x: 0.075
  y: 0.075

bar_cfg:
  size: 65
  opacity: 0.85
  margin: [10, *gap, 0, *gap]

bar_theme:
  background: *bg

groupbox_cfg:
  fontsize: 70
  margin_y: 3
  margin_x: 0
  padding_y: 6
  padding_x: 3
  borderwidth: 0
  disable_drag: True
  active: *fg
  inactive: *fg
  rounded: False
  highlight_method: "text"
  this_current_screen_border: *accent
  foreground: *fg

separator:
  linewidth: 1
  padding: 10
  foreground: *fg

net_cfg:
  font: *font
  fontsize: *font_size
  foreground: *fg
  padding: 0
  prefix: M
  use_bits: True
